# University Database Queries
Created: 09/15/2018
Latest Update: 09/15/2018
By: Can Bekleyici - bekleydata.com

## Introduction
This project goes through the complete process from database creation to SQL querying. In this example, a university database, that includes tables for <code>teacher</code>, <code>student</code>, <code>course</code>, and their relations <code>teaches</code> and <code>takes</code>, have been created using the Databse Management System (DBMS) <code>PostgreSQL</code>. A variety of queries have been conducted in order to get certain informations out of the database.

## Relational Database Model
The Database which has been created in this project will have the following scheme:

#### Student (firstname, name, major, <u>id</u>)
#### Teacher (firstname, name, department, <u>id</u>)
#### Course (name, semester, <u>id</u>)
#### teaches (<u><span style="border-bottom: 2px dotted #000;">teacher.id, course.id</span></u>)
#### takes (<u><span style="border-bottom: 2px dotted #000;">student.id, course.id</span></u>) 

## Database and Table Creation

First, a connection to the default postgresql database has to be made and our new database <code>university</code> has to be created and connected:

In [1]:
import pandas as pd
from sqlalchemy.engine import create_engine
%reload_ext sql
%config SqlMagic.autocommit=False
%sql postgresql://postgres:000000@localhost:5432/

engine = create_engine('postgresql://postgres:000000@localhost:5432/postgres')
            
conn = engine.connect()
conn.execute("commit")
conn.execute("create database university")
conn.close()

In [2]:
# connecting to the new 'university' database
%sql postgresql://postgres:000000@localhost:5432/university
engine = create_engine('postgresql://postgres:000000@localhost:5432/university')

Proceeding with creating the tables according to the scheme:

In [3]:
%%sql
CREATE TABLE student(
    firstname VARCHAR(64) NOT NULL,
    name VARCHAR(64) NOT NULL,
    major VARCHAR(64) NOT NULL,
    id INT NOT NULL,
    PRIMARY KEY (id)
);

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
Done.


[]

In [4]:
# confirm table creation
%sql SELECT * FROM student;

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
0 rows affected.


[]

In [5]:
%%sql
CREATE TABLE teacher(
    firstname VARCHAR(64) NOT NULL,
    name VARCHAR(64) NOT NULL,
    department VARCHAR(64) NOT NULL,
    id INT NOT NULL,
    PRIMARY KEY (id)
);

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
Done.


[]

In [6]:
%%sql
CREATE TABLE course(
    name VARCHAR(64) NOT NULL,
    id INT NOT NULL,
    semester VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
Done.


[]

In [7]:
%%sql
CREATE TABLE teaches(
    teacher INT NOT NULL,
    course INT NOT NULL,
    PRIMARY KEY(teacher, course), 
    FOREIGN KEY(teacher) REFERENCES teacher(id),
    FOREIGN KEY(course) REFERENCES course(id)
);

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
Done.


[]

In [8]:
%%sql
CREATE TABLE takes(
    student INT NOT NULL,
    course INT NOT NULL,
    PRIMARY KEY(student, course),
    FOREIGN KEY(student) REFERENCES student(id),
    FOREIGN KEY(course) REFERENCES course(id)
);

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
Done.


[]

## Entry Instertions

In [9]:
%%sql
INSERT INTO student (firstname,name,major,id)
VALUES
    ('Can','Bekleyici','Chinese',4916980),
    ('Bobby','Fisher','Mathematics',9834920),
    ('John','Kennedy','Politics',3872981),
    ('Michail','Tal','International Relation',1193209),
    ('Farrison','Hord','Archeology',4444444),
    ('Jack','Nicholson','Anthropology',5555555);

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
6 rows affected.


[]

In [10]:
%%sql
INSERT INTO teacher (firstname,name,department,id)
VALUES
    ('Angela','Merkel','Chemistry',11093),
    ('Donald','Trump','Philosophy',20981),
    ('Jinping','Xi','Art History',91932),
    ('Emmanuel','Macron','Economics',30928),
    ('Justin','Trudeau','Philosophy',33988),
    ('Vladimir','Putin','Gender Studies',98721);

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
6 rows affected.


[]

In [11]:
%%sql
INSERT INTO course (name,semester,id)
VALUES
    ('Human Ressource','Summer18',101),
    ('Python for Machine Learning I','Winter18',102),
    ('Python for Machine Learning II','Summer18',103),
    ('Statistics','Summer18',104),
    ('Chinese I','Summer17',105),
    ('Chinese II','Winter18',106),
    ('Chinese III','Summer18',107),
    ('World History','Summer18',108),
    ('Accounting','Winter18',109),
    ('Controling','Summer18',110),
    ('Marketing','Summer18',111);

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
11 rows affected.


[]

In [12]:
%%sql
INSERT INTO teaches (teacher,course)
VALUES
    (11093,101),
    (20981,102),
    (98721,103),
    (11093,104),
    (33988,105),
    (33988,106),
    (30928,107),
    (91932,108),
    (20981,109),
    (91932,110),
    (98721,111);

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
11 rows affected.


[]

In [13]:
%%sql
INSERT INTO takes (student,course)
VALUES
    (4916980,109),
    (4916980,102),
    (4916980,104),
    (4916980,101),
    (9834920,103),
    (9834920,111),
    (9834920,110),
    (3872981,101),
    (3872981,104),
    (3872981,103),
    (3872981,105),
    (1193209,103),
    (1193209,102),
    (1193209,108),
    (4444444,103),
    (4444444,111),
    (5555555,106),
    (5555555,107);

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
18 rows affected.


[]

## Display the Tables

In [34]:
%sql SELECT * FROM student;

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
5 rows affected.


[('Can', 'Bekleyici', 'Chinese', 4916980),
 ('Bobby', 'Fisher', 'Mathematics', 9834920),
 ('John', 'Kennedy', 'Politics', 3872981),
 ('Michail', 'Tal', 'International Relation', 1193209),
 ('Farrison', 'Hord', 'Archeology', 4444444)]

In [35]:
%sql SELECT * FROM teacher;

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
5 rows affected.


[('Angela', 'Merkel', 'Chemistry', 11093),
 ('Jinping', 'Xi', 'Art History', 91932),
 ('Emmanuel', 'Macron', 'Economics', 30928),
 ('Justin', 'Trudeau', 'Philosophy', 33988),
 ('Vladimir', 'Putin', 'Gender Studies', 98721)]

In [36]:
%sql SELECT * FROM course;

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
11 rows affected.


[('Human Ressource', 101, 'Summer18'),
 ('Python for Machine Learning I', 102, 'Winter18'),
 ('Python for Machine Learning II', 103, 'Summer18'),
 ('Statistics', 104, 'Summer18'),
 ('Chinese I', 105, 'Summer17'),
 ('Chinese II', 106, 'Winter18'),
 ('Chinese III', 107, 'Summer18'),
 ('World History', 108, 'Summer18'),
 ('Accounting', 109, 'Winter18'),
 ('Controling', 110, 'Summer18'),
 ('Marketing', 111, 'Summer18')]

Joined tables for the relations:

In [37]:
%sql SELECT * FROM student, takes WHERE student.id = takes.student;

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
16 rows affected.


[('Can', 'Bekleyici', 'Chinese', 4916980, 4916980, 109),
 ('Can', 'Bekleyici', 'Chinese', 4916980, 4916980, 102),
 ('Can', 'Bekleyici', 'Chinese', 4916980, 4916980, 104),
 ('Can', 'Bekleyici', 'Chinese', 4916980, 4916980, 101),
 ('Bobby', 'Fisher', 'Mathematics', 9834920, 9834920, 103),
 ('Bobby', 'Fisher', 'Mathematics', 9834920, 9834920, 111),
 ('Bobby', 'Fisher', 'Mathematics', 9834920, 9834920, 110),
 ('John', 'Kennedy', 'Politics', 3872981, 3872981, 101),
 ('John', 'Kennedy', 'Politics', 3872981, 3872981, 104),
 ('John', 'Kennedy', 'Politics', 3872981, 3872981, 103),
 ('John', 'Kennedy', 'Politics', 3872981, 3872981, 105),
 ('Michail', 'Tal', 'International Relation', 1193209, 1193209, 103),
 ('Michail', 'Tal', 'International Relation', 1193209, 1193209, 102),
 ('Michail', 'Tal', 'International Relation', 1193209, 1193209, 108),
 ('Farrison', 'Hord', 'Archeology', 4444444, 4444444, 103),
 ('Farrison', 'Hord', 'Archeology', 4444444, 4444444, 111)]

In [33]:
%sql SELECT * FROM teacher, teaches WHERE teacher.id = teaches.teacher;

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
9 rows affected.


[('Angela', 'Merkel', 'Chemistry', 11093, 11093, 101),
 ('Vladimir', 'Putin', 'Gender Studies', 98721, 98721, 103),
 ('Angela', 'Merkel', 'Chemistry', 11093, 11093, 104),
 ('Justin', 'Trudeau', 'Philosophy', 33988, 33988, 105),
 ('Justin', 'Trudeau', 'Philosophy', 33988, 33988, 106),
 ('Emmanuel', 'Macron', 'Economics', 30928, 30928, 107),
 ('Jinping', 'Xi', 'Art History', 91932, 91932, 108),
 ('Jinping', 'Xi', 'Art History', 91932, 91932, 110),
 ('Vladimir', 'Putin', 'Gender Studies', 98721, 98721, 111)]

## Deletion of Entries
for showcase purposes, certain entries have been dropped from the tables:

In [17]:
%%sql
DELETE FROM takes WHERE student=5555555;
DELETE FROM student WHERE id=5555555;

DELETE FROM teaches WHERE teacher=20981;
DELETE FROM teacher WHERE id=20981;

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
2 rows affected.
1 rows affected.
2 rows affected.
1 rows affected.


[]

## SQL Queries

The following part will conduct SQL queries on the created database to answer random questions about the data.
<hr>

Gives out every student (first name, name, id), who has taken a certain course (Statistics, id: 104) :

In [18]:
%%sql query <<
SELECT firstname, name, id
FROM student, takes
WHERE id = student
AND course = 104;

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
2 rows affected.
Returning data to local variable query


In [19]:
query

[('Can', 'Bekleyici', 4916980), ('John', 'Kennedy', 3872981)]

Gives out every teacher (first name and surname) who has ever tought a certain student (Bobby Fisher, id: 9834920):

In [20]:
%%sql query <<
SELECT DISTINCT firstname, name
FROM teacher AS t, teaches AS ts, takes AS tk
WHERE ts.course = tk.course
AND id = teacher
AND student = 9834920;

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
2 rows affected.
Returning data to local variable query


In [21]:
query

[('Jinping', 'Xi'), ('Vladimir', 'Putin')]

Gives out every course of a student (Farrison Hord, 4444444), which he is or she took in Summer 2018 :

In [22]:
%%sql query <<
SELECT c.name, c.semester
FROM course AS c, takes AS tk
WHERE c.id = tk.course
AND student = 4444444
AND c.semester = 'Summer18';

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
2 rows affected.
Returning data to local variable query


In [23]:
query

[('Python for Machine Learning II', 'Summer18'), ('Marketing', 'Summer18')]

Gives out the number of semesters, in which a teacher (Vladimir Putin, 98721) has held a course :

In [24]:
%%sql query <<
SELECT COUNT(DISTINCT semester)
FROM teaches AS ts, course AS c
WHERE c.id = ts.course
AND teacher = 98721;

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
1 rows affected.
Returning data to local variable query


In [25]:
query

[(1,)]

Gives out the first 5 students (id, name, firstname) in an alphabetically ordered table by name and first name :

In [26]:
%%sql
SELECT id, name, firstname
FROM student
ORDER BY name, firstname LIMIT 5;

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
5 rows affected.


[(4916980, 'Bekleyici', 'Can'),
 (9834920, 'Fisher', 'Bobby'),
 (4444444, 'Hord', 'Farrison'),
 (3872981, 'Kennedy', 'John'),
 (1193209, 'Tal', 'Michail')]

Gives out the number of different courses, which have been taken in the summer semester 2018:

In [27]:
%%sql
SELECT COUNT(DISTINCT c.id)
FROM course AS c, takes AS tk
WHERE c.id = tk.course
AND semester = 'Summer18';

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
1 rows affected.


[(6,)]

Gives out the number of students, which have been tought by each teacher in the summer semester 2018:

In [28]:
%%sql
SELECT t.name, COUNT(DISTINCT s.id)
FROM teacher AS t, teaches AS ts, takes AS tk, student AS s, course AS c
WHERE ts.course = tk.course
AND s.id = tk.student
AND t.id = ts.teacher
AND c.id = tk.course
AND c.id = ts.course
AND c.semester = 'Summer18'
GROUP BY t.name;

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
3 rows affected.


[('Merkel', 2), ('Putin', 4), ('Xi', 2)]

Gives out the name of the course, in which the number of participating students is the highest:

In [29]:
%%sql
SELECT c.name, COUNT(DISTINCT s.id)
FROM course AS c, takes AS tk, student AS s
WHERE c.id = tk.course
AND tk.student = s.id
GROUP BY c.name
ORDER BY COUNT(DISTINCT s.id) DESC
LIMIT 1;

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
1 rows affected.


[('Python for Machine Learning II', 4)]

Gives out the students (name, firstname, id), which have taken courses with either more than 5 or less than 3 students:

In [30]:
%%sql
SELECT course
INTO s_course 
FROM takes
GROUP BY course
HAVING COUNT(DISTINCT student) < 3 OR COUNT(DISTINCT student) > 5;

SELECT DISTINCT name, firstname, s.id
FROM student AS s, takes AS tk, s_course
WHERE s.id = tk.student
AND tk.course = s_course.course;

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
8 rows affected.
5 rows affected.


[('Fisher', 'Bobby', 9834920),
 ('Kennedy', 'John', 3872981),
 ('Bekleyici', 'Can', 4916980),
 ('Hord', 'Farrison', 4444444),
 ('Tal', 'Michail', 1193209)]

Gives out every teacher, who have never tought a certain student (Bobby Fisher):

In [31]:
%%sql
SELECT t.name, t.firstname, t.department, t.id
FROM teacher AS t
EXCEPT
SELECT t.name, t.firstname, t.department, t.id
FROM teacher AS t, teaches AS ts, takes AS tk, student AS s
WHERE ts.course = tk.course
AND tk.student = s.id
AND ts.teacher = t.id
AND s.name = 'Fisher'
AND s.firstname = 'Bobby';

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
3 rows affected.


[('Macron', 'Emmanuel', 'Economics', 30928),
 ('Merkel', 'Angela', 'Chemistry', 11093),
 ('Trudeau', 'Justin', 'Philosophy', 33988)]

Gives out every course and the number of its participants while only student id's above 4000000 are counted in:

In [32]:
%%sql
SELECT c.name, c.id, COUNT(DISTINCT s)
FROM course AS c, takes AS tk, student AS s
WHERE s.id > 4000000
AND c.id = tk.course
AND tk.student = s.id
GROUP BY c.name, c.id
ORDER BY COUNT(DISTINCT s);

   postgresql://postgres:***@localhost:5432/
 * postgresql://postgres:***@localhost:5432/university
7 rows affected.


[('Statistics', 104, 1),
 ('Python for Machine Learning I', 102, 1),
 ('Accounting', 109, 1),
 ('Controling', 110, 1),
 ('Human Ressource', 101, 1),
 ('Python for Machine Learning II', 103, 2),
 ('Marketing', 111, 2)]

## Conclusion

This project has showcased how a PostgreSQL database can be created an accessed using SQL. Some basic Query techniques have been shown in order to explore the database tables and their relations.